Create gamev1.py
artoorio/game1 pull request #2
Opened 2019-11-11 14:31 UTC by artoorio

class Player:
    def __init__(self, ):
        self.nums = {}
        self.answer = 0
        self.history = []
        self.win = None
        
    def make_step(self,num_in : 'Last step number', num_win : 'Number for win'):
        
        '''описание логики выбора хода''' 
        
        return num_in+1
    
    def collecting_points(self):
        'получение очков за игру'
        return
    
    
class Game:
    
    def __init__(self, start: 'BeginingNumber', finish : 'NumberForWin', players: 'List[Player]'): 

        self.start = start
        self.finish = finish
        self.players = players
        self.step_result = None
        self.last_step = start
    
    def play(self):
        
        '''сначала играем, а потом раздаем очки'''
        
        while self.step_result < self.finish:
            for player in self.players:
                self.step_result = player.make_step(self.last_step,self.finish) # вот мы используем метод игрока в игре
                if self.step_result >= self.finish: #если кто то победил, то заканчиваем цикл
                    break
                self.last_step = self.step_result #
                
        for player in self.players:
            player.collecting_points() #раздача очков

2019-11-13 10:17 UTC, ikuzart requested changes

2019-11-13 10:17 UTC, ikuzart commented on gamev1.py
> +    def make_step(self,num_in : 'Last step number', num_win : 'Number for win'):
Прочитай про type hints и переделай https://stackoverflow.com/questions/32557920/what-are-type-hints-in-python-3-5

2019-11-13 10:17 UTC, ikuzart commented on gamev1.py
> +
опрделись уже, у тебя пробел или нет после объявления класса

2019-11-13 10:17 UTC, ikuzart commented on gamev1.py
> +        '''описание логики выбора хода'''
прочитай https://www.python.org/dev/peps/pep-0257/ и переделай

2019-11-13 10:17 UTC, ikuzart commented on gamev1.py
> +        '''сначала играем, а потом раздаем очки'''
https://www.python.org/dev/peps/pep-0257/

2019-11-13 10:17 UTC, ikuzart commented on gamev1.py
> +        self.answer = 0
None, 0 это уже какое-то значение, а у тебя ответа пока нет

2019-11-13 10:17 UTC, ikuzart commented on gamev1.py
> +        'получение очков за игру'
https://www.python.org/dev/peps/pep-0257/

2019-11-13 10:17 UTC, ikuzart commented on gamev1.py
> +        self.last_step = start
последний шаг == старт, не логично. не успел стартовать и уже последний шаг. Именования должно отображать суть
Именование переменных это одна из самых сложных вещей в программировании))

2019-11-13 10:17 UTC, ikuzart commented on gamev1.py
> +        self.finish = finish
почему бы сразу не назвать переменную number_for_win и по условиям это константа, так что
`NUMBER_FOR_WIN = 24` и давай ее сделаем константой класса. Чем переменные класса от переменных объекта отличаются нужно объяснить?

2019-11-13 10:17 UTC, ikuzart commented on gamev1.py
> +                self.step_result = player.make_step(self.last_step,self.finish) # вот мы используем метод игрока в игре
убери комменты, у тебя целый язык есть что бы описать логику. это типа "эх, я не знаю как использовать язык программирования, напишу просто коммент, наверное разберутся"

2019-11-13 10:17 UTC, ikuzart commented on gamev1.py
> +                if self.step_result >= self.finish: #если кто то победил, то заканчиваем цикл
Что произойдет если мы просто уберем это условие? как будет себя вести while?

2019-11-13 15:15 UTC, artoorio commented on gamev1.py
> +                self.step_result = player.make_step(self.last_step,self.finish) # вот мы используем метод игрока в игре
это был твой коммент, ты меня подставил

2019-11-13 15:21 UTC, artoorio commented on gamev1.py
> +                if self.step_result >= self.finish: #если кто то победил, то заканчиваем цикл
Если уберем условие, то если игрок сделал ход первым и победил - остальные все равно сделают свои ходы (т.е. всегда будет проходить полный круг ходов). Т.е. если кто то победил, то остальным не нужно делать ходы.

2019-11-13 15:25 UTC, artoorio commented on gamev1.py
> +        'получение очков за игру'
тут в чем ошибка?

2019-11-13 15:29 UTC, artoorio commented on gamev1.py
> +        self.finish = finish
константы класса не изучал

2019-11-13 15:33 UTC, ikuzart commented on gamev1.py
> +                if self.step_result >= self.finish: #если кто то победил, то заканчиваем цикл
тогда условие в while не имеет особого значения, оно должно быть True, пока не выйдем из цикла
```
while True:
    for player in self.players:
        self.step_result = player.make_step(self.last_step,self.finish) 
    if self.step_result >= self.finish:
        break;
```

2019-11-13 15:34 UTC, ikuzart commented on gamev1.py
> +        'получение очков за игру'
Стиль dockstring'а

2019-11-13 15:38 UTC, artoorio commented on gamev1.py
> +                if self.step_result >= self.finish: #если кто то победил, то заканчиваем цикл
логично, а как он станет False?

2019-11-13 15:39 UTC, artoorio commented on gamev1.py
> +        'получение очков за игру'
` '''получение очков за игру'''`
так нужно было?

2019-11-13 15:39 UTC, ikuzart commented on gamev1.py
> +                if self.step_result >= self.finish: #если кто то победил, то заканчиваем цикл
Никак, это бесконечный цикл, но ты из него выходишь, только если выпольняется условие

2019-11-13 15:41 UTC, ikuzart commented on gamev1.py
> +        'получение очков за игру'
"""получение очков за игру"""

2019-11-13 15:42 UTC, artoorio commented on gamev1.py
> +                if self.step_result >= self.finish: #если кто то победил, то заканчиваем цикл
не могу врубиться как в таком виде оформить

2019-11-13 15:43 UTC, ikuzart commented on gamev1.py
> +                if self.step_result >= self.finish: #если кто то победил, то заканчиваем цикл
я же тебе код скинул, комментов выше

2019-11-13 15:43 UTC, artoorio commented on gamev1.py
> +        'получение очков за игру'
принято

2019-11-13 15:44 UTC, ikuzart commented on gamev1.py
> +        self.finish = finish
а в чем разница класса и объекта понимаешь?

2019-11-13 15:46 UTC, artoorio commented on gamev1.py
> +                if self.step_result >= self.finish: #если кто то победил, то заканчиваем цикл
так он улетит в бесконечность, где выход то? break остановит только цикл `for`

2019-11-13 15:49 UTC, artoorio commented on gamev1.py
> +        self.finish = finish
класс ~ тип
объект ~ переменная

соотношения такие

2019-11-13 16:16 UTC, ikuzart commented on gamev1.py
> +                if self.step_result >= self.finish: #если кто то победил, то заканчиваем цикл
да, тупанул)) тогда норм

я бы наверное так написал
```
win = False
while not win:
    for player in self.players:
        self.step_result = player.make_step(self.last_step, self.finish)
        if self.step_result >= self.finish:
            win = True
            break
```

2019-11-13 16:18 UTC, ikuzart commented on gamev1.py
> +        self.finish = finish
нуу, что-то вроде этого, но несовсем, надо будет рассказать тебе про классы, объекты и переменные лучше голосом как-нибудь

2019-11-18 13:15 UTC, ikuzart approved these changes
ок, мердж в мастер

2019-11-18 13:16 UTC, merged